version: '3.9'

services:
  postgres:
    image: postgres:13.8
    ports:
      - "5432:5432"
    env_file:
      - ./webservices/.env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    env_file:
      - ./webservices/.env
    entrypoint: /app/docker/backend/wsgi-entrypoint.sh
    # https://stackoverflow.com/questions/32022014/auto-reloading-of-code-changes-with-django-development-in-docker-with-gunicorn
    volumes:
      - ./shared:/tmp
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:3.2
    ports:
     - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    env_file:
      - ./webservices/.env
    entrypoint: /app/docker/worker/worker-entrypoint.sh
    volumes:
      - ./shared:/tmp
      - .:/app
    depends_on:
      - postgres
      - redis
      - rabbitmq

  # scheduler:
  #   build:
  #     context: .
  #     dockerfile: ./docker/backend/Dockerfile
  #   env_file:
  #     - ./webservices/.env
  #   entrypoint: /app/docker/scheduler/scheduler-entrypoint.sh
  #   volumes:
  #     - ./shared:/tmp
  #     - .:/app
  #   depends_on:
  #     - postgres
  #     - redis
  #     - rabbitmq