version: '3.9'

services:
  postgres:
    image: postgres:13.8
    ports:
      - '5432:5432'
    env_file:
      - ./webservices/.env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: ./docker/webservices/Dockerfile
    env_file:
      - ./webservices/.env
    entrypoint: /app/docker/webservices/wsgi-entrypoint.sh
    volumes:
      - static_volume:/app/webservices/server/django_static
      - ./shared:/tmp
    expose:
      - 8000
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:3.2
    ports:
     - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    build:
      context: .
      dockerfile: ./docker/webservices/Dockerfile
    entrypoint: /app/docker/worker/worker-entrypoint.sh
    env_file:
      - ./webservices/.env
    volumes:
      - ./shared:/tmp
    depends_on:
      - postgres
      - redis
      - rabbitmq

  # scheduler:
  #   build:
  #     context: .
  #     dockerfile: ./docker/webservices/Dockerfile
  #   entrypoint: /app/docker/scheduler/scheduler-entrypoint.sh
  #   env_file:
  #     - ./webservices/.env
  #   volumes:
  #     - ./shared:/tmp
  #   depends_on:
  #     - postgres
  #     - redis
  #     - rabbitmq

volumes:
  static_volume: {}
